version: "3"
services:
  db:
    image: postgres
    container_name: pgdb
    ports:
      - 5432:5432
    environment: 
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
    restart: unless-stopped
    volumes:
      - ./dellstore2-normal-1.0.sql:/docker-entrypoint-initdb.d/dellstore2-normal-1.0.sql

    healthcheck:
      test: pg_isready -U postgres
      interval: 10s
      timeout: 5s
      retries: 5
  jup:
    container_name: jup
    image: poteroa/jupyter:jupyter
    volumes:
      - ./work/:/home/jovyan/work
    entrypoint: ["ipython", "-c", "'%run work/runnb.py'"]
    depends_on:
      - db
  dash:
    image: poteroa/dockerdash:dash
    restart: unless-stopped
    ports:
      - 8888:8888
    container_name: dash
    depends_on:
      - jup
    volumes:
      - ./work/:/app
    command: sleep 40 s && python /app/app.py
